### ISSUE TITLE
[BUG] Exception generated, when trying to use bchjs.SLP.Utils.balance() function

### ISSUE THREAD

**Issue by zh** [Permissionless-Software-Foundation/bch-api#10]
### Problem:

When tried to use bch-js `bchjs.SLP.Utils.balance()` function there was an error message, for invalid function usage in `bch-api`:

```
error: 'TypeError: _this.bchjs.SLP.Address.toSlpAddress is not a function\n' +
    '    at balancesForAddressByTokenID (/home/safeuser/bch-api/src/routes/v3/slp.js:883:47)\n' +
    '    at Layer.handle [as handle_request] (/home/safeuser/bch-api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/home/safeuser/bch-api/node_modules/express/lib/router/route.js:137:13)\n' +
    '    at Route.dispatch (/home/safeuser/bch-api/node_modules/express/lib/router/route.js:112:3)\n' +
    '    at Layer.handle [as handle_request] (/home/safeuser/bch-api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at /home/safeuser/bch-api/node_modules/express/lib/router/index.js:281:22\n' +
    '    at param (/home/safeuser/bch-api/node_modules/express/lib/router/index.js:354:14)\n' +
    '    at param (/home/safeuser/bch-api/node_modules/express/lib/router/index.js:365:14)\n' +
    '    at param (/home/safeuser/bch-api/node_modules/express/lib/router/index.js:365:14)\n' +
    '    at Function.process_params (/home/safeuser/bch-api/node_modules/express/lib/router/index.js:410:3)'
```

### How to reproduce:

Patch the SLP integration tests with a test for the method:

```diff
diff --git a/test/integration/slp.js b/test/integration/slp.js
index a641a21..98f6522 100644
--- a/test/integration/slp.js
+++ b/test/integration/slp.js
@@ -439,6 +439,18 @@ describe(`#SLP`, () => {
       })
     })

+    describe.only("#balance", () => {
+      it(`should fetch balance for particular token on address: simpleledger:qzv3zz2trz0xgp6a96lu4m6vp2nkwag0kvyucjzqt9`, async () => {
+        const balance = await bchjs.SLP.Utils.balance(
+          "simpleledger:qzv3zz2trz0xgp6a96lu4m6vp2nkwag0kvyucjzqt9",
+          "4de69e374a8ed21cbddd47f2338cc0f479dc58daa2bbe11cd604ca488eca0ddf" // spice
+        )
+        console.log(`balance: ${JSON.stringify(balance, null, 2)}`)
+
+        assert.equal(true, false, "Will never come here - exception will be generated before.")
+      })
+    })
+
     describe("#balancesForAddress", () => {
       it(`should throw an error if input is not a string or array of strings`, async () => {
         try {
```

and start the test with: `npm run test:integration`.

### Additional information

Looking on the file from the error message above `bch-api/src/routes/v3/slp.js` , line 883, there is non-included in `try {} catch {}` block function call:

```js
const slpAddr = _this.bchjs.SLP.Address.toSlpAddress(req.params.address)
```

but maybe this is just part of the problem. Can be something wrong with `req.params.address` too...

**Comment by christroutner** [comment]
Thanks for calling this out. That `.balance()` endpoint was deprecated when the code base moved to SLPDB v1, but it was never removed. The code was removed in PR #11, and another PR to remove the call in bch-js.

You ultimately found and used the correct endpoint, which is `balanceForAddress()`.
